using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChainConnext.Shared.BD
{
    public class BD_MastCont : BaseShared
    {
        public string? RefNo { get; set; }
        public string? CONTNO { get; set; }
        public string? TYPE { get; set; }
        public string? CASHCODE { get; set; }
        public DateTime? EFFDATE { get; set; }
        public DateTime? STDATE { get; set; }
        public string? HOMETYPE { get; set; }
        public DateTime? NEXTDUE { get; set; }
        public int NEXTPERIOD { get; set; }
        public DateTime? PAYDATE { get; set; }
        public string? PAYDAY { get; set; }
        public string? MODE { get; set; }
        public string? COMPANY { get; set; }
        public string? SERIALNO { get; set; }
        public string? MODEL { get; set; }
        public string? SPECCODE { get; set; }
        public string? RECEIPTNO { get; set; }
        public string? BOOKNO { get; set; }
        public string? PAYPERIOD { get; set; }
        public string? PAYTYPE { get; set; }
        public decimal PREMIUM { get; set; }
        public decimal SALES { get; set; }
        public decimal TOTALPAY { get; set; }
        public string? SALECODE { get; set; }
        public string? STATUS { get; set; }
        public string? RESERVED { get; set; }
        public DateTime? ENTERDATE { get; set; }
        public bool CHK { get; set; }
        public string? USERKEY { get; set; }
        public DateTime? MEETDATE { get; set; }
        public string? CHECKER { get; set; }
        public decimal CREDIT { get; set; }
        public string? SERVICE { get; set; }
        public DateTime? OpenDate { get; set; }
        public DateTime? CloseDate { get; set; }
        public DateTime? FirstDate { get; set; }
        public decimal Balance { get; set; }
        public decimal Disc { get; set; }
        public string? SModel { get; set; }
        public string? SMth { get; set; }
        public string? SYear { get; set; }
        public string? SRun { get; set; }
        public string? DocDisc { get; set; }
        public string? Posted { get; set; }
        public string? Errs { get; set; }
        public string? PrnSt { get; set; }
        public DateTime? PrnDate { get; set; }
        public string? Paid { get; set; }
        public string? ContNo2 { get; set; }
        public DateTime? GlDate { get; set; }
        public decimal UCost { get; set; }
        public decimal UR { get; set; }
        public decimal UV { get; set; }
        public string? Book { get; set; }
        public string? AccNo { get; set; }
        public decimal Vat { get; set; }
        public decimal IncAmt { get; set; }
        public decimal DrAmt { get; set; }
        public string? IsGL { get; set; }
        public string? IsType { get; set; }
        public string? IsGroup { get; set; }
        public string? IsPost { get; set; }
        public decimal UInt { get; set; }
        public string? GLFlag { get; set; }
        public DateTime? VatDate { get; set; }
        public string? call { get; set; }
        public string? visit { get; set; }
        public string? docno { get; set; }
        public string? excstatus { get; set; }
        public DateTime? excdate { get; set; }
        public decimal vatbal { get; set; }
        public DateTime? vatlast { get; set; }
        public decimal vatpaid { get; set; }
        public DateTime? vatnext { get; set; }
        public DateTime? vatcur { get; set; }
        public decimal vatnet { get; set; }
        public DateTime? vatfirst { get; set; }
        public int vatnextp { get; set; }
        public int vatcurp { get; set; }
        public string? vatstop { get; set; }
        public string? vatrem { get; set; }
        public decimal vatpaid2 { get; set; }
        public decimal vatpaid1 { get; set; }
        public decimal netcredit { get; set; }
        public decimal nextcredit { get; set; }
        public decimal discfirst { get; set; }
        public decimal premium2 { get; set; }
        public string? SCode { get; set; }
        public string? svcontno { get; set; }
        public string? is_lock { get; set; }
        public string? tocode { get; set; }
        public string? torefno { get; set; }
        public string? tocontno { get; set; }
        public string? tonote { get; set; }
        public DateTime? todate { get; set; }
        public DateTime? todate1 { get; set; }
        public string? fromrefno { get; set; }
        public string? fromcontno { get; set; }
        public string? toacc { get; set; }
        public DateTime? toaccdate { get; set; }
        public string? toturn { get; set; }
        public DateTime? toturndate { get; set; }
        public string? errs1 { get; set; }
        public string? tovat { get; set; }
        public DateTime? tovatdate { get; set; }
        public string? svStatus { get; set; }
        public string? chanel { get; set; }
        public string? errs2 { get; set; }
        public string? empcode1 { get; set; }
        public string? empcode2 { get; set; }
        public string? empcode3 { get; set; }
        public DateTime? opendate1 { get; set; }
        public DateTime? opendate2 { get; set; }
        public DateTime? closedate1 { get; set; }
        public DateTime? closedate2 { get; set; }
        public string? hold1 { get; set; }
        public string? hold2 { get; set; }
        public string? hold3 { get; set; }
        public string? hold4 { get; set; }
        public string? hold5 { get; set; }
        public string? isedit { get; set; }
        public DateTime? editdate { get; set; }
        public string? editby { get; set; }
        public DateTime? keydate { get; set; }
        public string? tohead { get; set; }
        public DateTime? toheaddate { get; set; }
        public int ayear { get; set; }
        public int aperiodno { get; set; }
        public string? asalecode { get; set; }
        public string? comm { get; set; }
        public string? comm1 { get; set; }
        public string? comm2 { get; set; }
        public string? comm3 { get; set; }
        public string? comm4 { get; set; }
        public string? tosalecode { get; set; }
        public int cryear { get; set; }
        public int crperiod { get; set; }
        public string? isfull { get; set; }
        public string? isorigin { get; set; }
        public string? ispay { get; set; }
        public string? vip { get; set; }
        public string? ItemCode { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool is_toacc { get; set; }
        public bool is_change { get; set; }
        public string? CreatedBy { get; set; }
    }
}
